version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    restart: always
    volumes:
      - /apps/node_modules
      - ./apps/backend/:/app
    environment:
      - HOST=0.0.0.0
    ports:
      - 4000:4000
    networks:
      - app_network
  web:
    depends_on:
      - backend
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    restart: always
    volumes:
      - /apps/node_modules
      - ./apps/web/:/app
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true